services:
  bank-discovery-service:
    build: ./discoveryService
    container_name: bank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      retries: 10
  bank-config-service:
    build: ./configService
    container_name: bank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      bank-discovery-service:
          condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 20s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
  bank-customer-service:
    build: ./customerService
    container_name: bank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      bank-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 20s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://bank-config-service:9999/
  bank-account-service:
    build: ./accountService
    container_name: bank-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    depends_on:
      bank-customer-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 20s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://bank-config-service:9999/
  bank-gateway-service:
    build: ./gatewayService
    container_name: bank-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      bank-account-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 20s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://bank-config-service:9999/
  front-end:
    build: ./front-end
    container_name: front-end
    depends_on:
      bank-gateway-service:
        condition: service_healthy
    ports:
      - '80:80'
    expose:
      - '80'